version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      JWT_SECRET: secret
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src  
    command: sh -c "npx prisma migrate deploy && npm run dev"


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app          
      - /app/node_modules        
    command: npm run dev
    depends_on:
      - backend


volumes:
  db-data:
